print("Starting up...")
print("")
dofile("utils.lua")
--dofileifexists("HSL.lua")
dofileifexists("led.lua")
dofileifexists("webserver.lua")
dofileifexists("processcommand.lua")
--dofileifexists("pattern1.lua")
--dofileifexists("pattern2.lua")
--dofileifexists("pattern3.lua")
--dofileifexists("pattern4.lua")
--dofileifexists("pattern5.lua")
--dofileifexists("pattern6.lua")
--dofileifexists("pattern7.lua")
